### ISSUE TITLE
Incorrect content length sent

### ISSUE THREAD

**Issue by floyd-fuh** [albinowax/ActiveScanPlusPlus#21]
When I run https://github.com/pajswigger/content-length-fixer I will get alerted that ActiveScan++ sends incorrect Content-Length headers when it is doing a test request with `application/xml` as Content-Type, when it is using an Accept header of `../../../../../../../../../../../../../e*c/h*s*s{{` or using the Content-Type header of `${#context["com.opensymphony.xwork2.dispatcher.HttpServletResponse"].addHeader("X-Ack",2273*5098)}.multipart/form-data`

**Comment by albinowax** [comment]
Think I resolved this one in the Java rewrite
