### ISSUE TITLE
False positive: Quote consumption

### ISSUE THREAD

**Issue by aroly** [albinowax/ActiveScanPlusPlus#28]
Hi James,

As requested in Burp, I report a false positive for the "Suspicious input transformation: quote consumption". 

The request 1st line was something like: `GET /''/foo HTTP/2` which resulted in an expected 404 with the error message `The requested URL //''/foo was not found on this server.`. I guess the extension spotted a single quote and reported the issue, which is not correct in this case. 

Cheers,

A.

**Comment by albinowax** [comment]
Thanks for the report! Looks like there were supposed to be anchors on either side of the quote but they got lost in the rewrite. I've pushed a fix & updated the jar.
