### ISSUE TITLE
Apache Struts2 check

### ISSUE THREAD

**Issue by Green-Wolf** [albinowax/ActiveScanPlusPlus#8]
Activescan++ is super useful, but one of the checks for the Apache Struts 2 vuln is incomplete. I checked the code and its only checking the content-type header, but the content-disposition and content-length headers are vulnerable as well.

https://www.waratek.com/apache-struts-2-vulnerability/

**Comment by albinowax** [comment]
Thanks for the suggestion. ActiveScan++ is intended to be a lightweight scanner addon for finding some of the most common vulnerabilities. As such, I'll happily optimise payloads to make them as effective as possible but I'm not keen on adding additional payloads to gain a little extra coverage.
